movie/cards1/urls.py
from django.urls import path
from cards1 import views

app_name="cards1"
urlpatterns = [
    path('',views.home,name="home"),
    path('add',views.add,name="add"),
    path('view/<int:p>',views.view,name="view"),
    path('delete/<int:p>',views.delete,name="delete"),
    path('update/<int:p>',views.update,name="update"),




]

movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cards1.urls')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/cards1/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to="movies",null=True,blank=True)

    def __str__(self):
        return self.name

movie/cards1/forms.py
from django import forms
from cards1.models import Movie

#form definition
class movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields="__all__"

movie/cards1/views.py
from django.shortcuts import render
from cards1.models import Movie
from cards1.forms import movieform

# Create your views here.

def home(request):
    m=Movie.objects.all()
    return render(request,'home.html',{'m':m})
def add(request):
    if(request.method=="POST"):
        form=movieform(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return home(request)
    form=movieform()
    return render(request,'add.html',{'form':form})
def view(request,p):
    m=Movie.objects.get(id=p)
    return render(request,'view.html',{'m':m})
def delete(request,p):
    m=Movie.objects.get(id=p)
    m.delete()
    return home(request)
def update(request,p):
    m = Movie.objects.get(id=p)
    if (request.method == "POST"):
        form = movieform(request.POST, request.FILES,instance=m)
        if form.is_valid():
            form.save()
            return home(request)

    form=movieform(instance=m)

    return render(request,'update.html',{'form':form})

movie/templates/add.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<center>
    <h3> Movies </h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}

        <input type="submit">
    </form>
</center>
{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online Movie Store</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


          <a href="{% url 'cards1:add' %}" class="btn btn-cutline-danger">Add</a>

    </div>

</nav>
{% block content %}
{% endblock %}


</body>
</html>

movie/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
<div class="row">
    {% for i in m %}
    <div class="col-sm-4 " >
<div class="card" style="width:30rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="200px" width="100%" alt="...">
  <div class="card-body">
      <p class="card-id">{{i.id}}</p>
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
      <p class="card-text">{{i.year}}</p>
    <a href="{% url 'cards1:view' i.id %}" class="btn btn-primary">Details</a>
  </div>
</div>
</div>
{% endfor %}
    </div></div>
{% endblock %}

movie/templates/update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h3>Update Details</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>

        <input type="submit">
    </form>
</center>
{% endblock %}

movie/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>Movie details</h3>
<div class="row>">

     <div class="col-sm-4 " >
<div class="card" style="width:30rem;">
  <img src="{{m.image.url}}" class="card-img-top" height="200px" width="100%" alt="...">
  <div class="card-body">
      <p class="card-id">{{m.id}}</p>
    <h5 class="card-title">{{m.name}}</h5>
    <p class="card-text">{{m.desc}}</p>
      <p class="card-text">{{m.year}}</p>
    <a href="{% url 'cards1:update' m.id %}" class="btn btn-primary">Update</a>
      <a href="{% url 'cards1:delete' m.id %}" class="btn btn-primary">Delete</a>
  </div>
</div>
</div>

    </div>
{% endblock %}